apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: cronjob-logger
  annotations:
    version: v0.0.4
    description: 'An application with a provider and component built for extending wasmCloud with custom capabilities'
spec:
  components:
    - name: log-component
      type: component
      properties:
        image: file://./component/build/logger-component_s.wasm
      traits:
        - type: spreadscaler
          properties:
            instances: 1
    - name: second-log-component
      type: component
      properties:
        image: file://./component/build/logger-component_s.wasm
      traits:
        - type: spreadscaler
          properties:
            instances: 1


    - name: cronjob
      type: capability
      properties:
        image: europe-north1-docker.pkg.dev/artifacts-352708/map/cronjob-provider:0.0.1
        id: cronjob
      traits:
        - type: link
          properties:
            target: log-component
            namespace: mattilsynet
            package: test
            interfaces: [cron-handler]
            target_config:
              - name: cron-expression
                properties:
                  expression: "2 * *"
        - type: link
          properties:
            target: second-log-component
            namespace: mattilsynet
            package: test
            interfaces: [cron-handler]
            target_config:
              - name: cron-expression2
                properties:
                  expression: "5 * *"
