// Generated by `wit-bindgen-wrpc-go` 0.11.0. DO NOT EDIT!
package cronjob

import (
	context "context"
	fmt "fmt"
	slog "log/slog"
	wrpc "wrpc.io/go"
)

func CronHandler(ctx__ context.Context, wrpc__ wrpc.Invoker) (err__ error) {
	var w__ wrpc.IndexWriteCloser
	var r__ wrpc.IndexReadCloser
	w__, r__, err__ = wrpc__.Invoke(ctx__, "mattilsynet:cronjob/cronjob", "cron-handler", nil)
	if err__ != nil {
		err__ = fmt.Errorf("failed to invoke `cron-handler`: %w", err__)
		return
	}
	defer func() {
		if err := r__.Close(); err != nil {
			slog.ErrorContext(ctx__, "failed to close reader", "instance", "mattilsynet:cronjob/cronjob", "name", "cron-handler", "err", err)
		}
	}()
	if cErr__ := w__.Close(); cErr__ != nil {
		slog.DebugContext(ctx__, "failed to close outgoing stream", "instance", "mattilsynet:cronjob/cronjob", "name", "cron-handler", "err", cErr__)
	}
	return
}
